### ISSUE TITLE
panic while running job: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by TvMpt** [subfinder/subfinder#118] opened 2018-07-13 14:44 UTC
The application crashes with some domains, maybe invalid responses are not handled properly somewhere in code...

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: interface conversion: interface {} is runtime.errorString, not string
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6b9d9b]

goroutine 36 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc420074af0)
        /home/ec2-user/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x163
panic(0x717da0, 0x93b9f0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/subfinder/subfinder/libsubfinder/sources/ipv4info.Query(0xc4200e6a60, 0x2, 0x2, 0x68c801, 0x101)
        /home/ec2-user/go/src/github.com/subfinder/subfinder/libsubfinder/sources/ipv4info/ipv4info.go:99 +0x8fb
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc420096b40, 0xc420074af0)
        /home/ec2-user/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc420096b40, 0x11)
        /home/ec2-user/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
        /home/ec2-user/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f
```

**Comment by codingo** [comment] 2018-07-14 13:51
Can you supply further information? The flags you were using as well as your GO version would greatly aid in diagnosing this.

**Comment by codingo** [comment] 2018-07-16 11:04
Closing this due to a lack of information. Will re-open this if that changes.

**Comment by AnotherWayIn** [comment] 2018-07-17 09:41
I too am getting this since the latest update (might not be related, but it's the same on multiple instances). I'm running version go1.10.3

**Comment by Ice3man543** [comment] 2018-07-17 09:42
@AnotherWayIn could you provide some more context? The domain you were finding, the flags you used, etc.

**Comment by AnotherWayIn** [comment] 2018-07-17 09:46
any flags really. Interestingly it only fails on certain domains e.g. bbc.com

**Comment by codingo** [comment] 2018-07-17 09:52
A bit time poor this evening so I don't have a chance to try to reproduce this. Will do so if this is still outstanding tomorrow evening.

**Comment by AnotherWayIn** [comment] 2018-07-17 10:01
no problemo. thanks

**Comment by arbazkiraak** [comment] 2018-08-17 19:26
```:~# subfinder -d hackerone.com
===============================================
-=Subfinder v1.1.3 github.com/subfinder/subfinder
===============================================


Running Source: Ask
Running Source: Archive.is
Running Source: Baidu
Running Source: Bing
Running Source: CertDB
Running Source: CertificateTransparency
Running Source: Certspotter
Running Source: Commoncrawl
Running Source: Crt.sh
Running Source: Dnsdb
Running Source: DNSDumpster
Running Source: Dogpile
Running Source: Exalead
Running Source: Findsubdomains
Running Source: Googleter
Running Source: Hackertarget
Running Source: Ipv4Info
Running Source: PTRArchive
Running Source: Sitedossier
Running Source: Threatcrowd
Running Source: ThreatMiner
Running Source: WaybackArchive
Running Source: Yahoo

Running enumeration on hackerone.com
2018/08/17 19:25:04 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
        panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 56 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc42009e4b0)
        /root/go_projects/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x163
panic(0x716ea0, 0x93aa30)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/subfinder/subfinder/libsubfinder/sources/dnsdb.Query(0xc4201163c0, 0x2, 0x2, 0x68cc01, 0x940101)
        /root/go_projects/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdb/dnsdb.go:53 +0x70e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc42024c000, 0xc42009e4b0)
        /root/go_projects/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc42024c000, 0x4)
        /root/go_projects/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
        /root/go_projects/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f```


=================================

> # go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go_projects"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build045286262=/tmp/go-build -gno-record-gcc-switches"

=========================================

:~# go version
go version go1.10.3 linux/amd64

**Comment by arbazkiraak** [comment] 2018-08-17 19:34
* Tool used to work fine but I'm getting same error since last night. I have rebooted & installed again from clone . Error remains same

**Comment by arbazkiraak** [comment] 2018-08-17 19:38
PC config : 
16 Gb ram, 
6 vCPUs

**Comment by eur0pa** [comment] 2018-08-17 20:27
Can confirm the same. Reverting to an older build **does not** solve the issue.

```
Running enumeration on x
2018/08/17 22:22:02 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 33 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc420074a00)
	/home/europa/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x163
panic(0x716ea0, 0x93aa30)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/subfinder/subfinder/libsubfinder/sources/dnsdb.Query(0xc4200e6a00, 0x2, 0x2, 0x68cc01, 0x101)
	/home/europa/go/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdb/dnsdb.go:53 +0x70e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc420094c80, 0xc420074a00)
	/home/europa/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc420094c80, 0xe)
	/home/europa/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
	/home/europa/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f
```

**Comment by anshumanbh** [comment] 2018-08-18 01:32
@Mzack9999 Doesn't look like the fix worked? I pulled in the latest code with the fix, built a new image and ran. I am still seeing the same error:

```
2018/08/18 00:29:16 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 75 [running]:
app/vendor/github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc420066960)
	/go/src/app/vendor/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x19c
panic(0x729540, 0x948c40)
	/usr/local/go/src/runtime/panic.go:491 +0x283
app/vendor/github.com/subfinder/subfinder/libsubfinder/sources/dnsdb.Query(0xc4200c8a00, 0x2, 0x2, 0x699b01, 0x101)
	/go/src/app/vendor/github.com/subfinder/subfinder/libsubfinder/sources/dnsdb/dnsdb.go:53 +0x7df
app/vendor/github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc42007cc80, 0xc420066960)
	/go/src/app/vendor/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
app/vendor/github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc42007cc80, 0x10)
	/go/src/app/vendor/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by app/vendor/github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
	/go/src/app/vendor/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f
```

**Comment by Mzack9999** [comment] 2018-08-18 04:00
@anshumanbh could you please double check you are running the latest version, eventually trying to prune the docker images?

**Comment by anshumanbh** [comment] 2018-08-18 05:44
Just sent a PR regarding the Docker build

**Comment by jaikishantulswani** [comment] 2018-08-22 09:47
Getting the same issue, meanwhile the ad-hoc fix from @eur0pa is working 

`2018/08/22 15:14:20 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 40 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0x19f206c0)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x153
panic(0x82ef660, 0x84bf060)
	/usr/local/go/src/runtime/panic.go:505 +0x1dc
github.com/subfinder/subfinder/libsubfinder/sources/dnsdb.Query(0x19e0c330, 0x2, 0x2, 0x826f001, 0x84c0101)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdb/dnsdb.go:53 +0x5f3
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0x19f46000, 0x19f206c0)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x59
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0x19f46000, 0x11)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0x90
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x65
`
Go Version
`go version go1.10 linux/386
`

**Comment by Mzack9999** [comment] 2018-08-22 10:00
@jaikishantulswani looks like you are using an old version of subfinder, please see #138

**Comment by jaikishantulswani** [comment] 2018-08-23 07:54
@Mzack9999 ,
Thanks it works but with this issue -
dnsdb: Unexpected return status 503

**Closed** 2018-08-24 02:51 UTC
Labels: bug

**Comment by Mzack9999** [comment] 2018-08-24 10:50
@jaikishantulswani this is expected, please read [here](https://github.com/subfinder/subfinder/issues/137#issuecomment-414273473)
